DBI.Safety/DBI.Safety/Controllers/SOCController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using DBI.Safety.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Dapper;
using System.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using System.ComponentModel;
using DBI.Safety.Helper;

namespace DBI.Safety.Controllers
{
    public class SOCController : Controller
    {
        private readonly IConfiguration configuration;
        public SOCController(IConfiguration config)
        {
            this.configuration = config;
        }

        public SOCForm GetSOCForm(SOCForm activeForm = null)
        {
            SOCForm form = new SOCForm();
            SqlConnection conn = new SqlConnection();
            conn.ConnectionString = configuration.GetConnectionString("DefaultConnection");
            using (IDbConnection dbConnection = conn)
            {
                dbConnection.Open();
                var questions = dbConnection.Query<QuestionsFormViewModel>(@"SELECT d.Id, d.Name, c.Name AS Category, d.SortOrderId
                    FROM Dictionary d
                    INNER JOIN Category c ON d.CategoryId = c.Id 
                    INNER JOIN Form f ON c.FormId = f.Id
                    WHERE f.Name = 'SOC' AND c.Description = 'Question' AND 
                    d.IsActive = 1 AND c.IsActive = 1 AND f.IsActive = 1
                    ORDER BY c.SortOrderId, d.SortOrderId");
                form.Questions = new List<QuestionsFormViewModel>();

                foreach (var item in questions)
                {
                    var possibleAnswers = dbConnection.Query<dynamic>(
                    @"SELECT d.Id, d.Name AS Text
                    FROM Dictionary d
                    INNER JOIN Category c ON d.CategoryId = c.Id
                    INNER JOIN Form f ON c.FormId = f.Id
                    WHERE f.Name = 'SOC' AND c.Name = 'Answer' AND 
                    d.IsActive = 1 AND c.IsActive = 1 AND f.IsActive = 1").ToList();

                    var possibleAnswerList = new List<Answer>();
                    foreach (var aItem in possibleAnswers)
                    {
                        possibleAnswerList.Add(new Answer { Id = aItem.Id, Text = aItem.Text });
                    }

                    if (activeForm != null)
                    {
                        foreach (var q in activeForm.Questions)
                        {
                            if(item.Id == q.Id)
                            {
                                form.Questions.Add(new QuestionsFormViewModel
                                {
                                    Id = item.Id,
                                    Name = item.Name,
                                    Category = item.Category,
                                    SortOrderId = item.SortOrderId,
                                    PossibleAnswers = possibleAnswerList,
                                    SelectedAnswer = q.SelectedAnswer
                                });
                                break;
                            }                            
                        }
                        form.IsQuestionSelected = activeForm.IsQuestionSelected;
                        form.IsLocationEnabled = activeForm.IsLocationEnabled;
                    }
                    else
                    {
                        form.Questions.Add(new QuestionsFormViewModel
                        {
                            Id = item.Id,
                            Name = item.Name,
                            Category = item.Category,
                            SortOrderId = item.SortOrderId,
                            PossibleAnswers = possibleAnswerList
                        });
                        form.IsQuestionSelected = true;
                        form.IsLocationEnabled = true;
                    }                               
                }                

                var possibleObserverType = dbConnection.Query<dynamic>(
                    @"SELECT d.Id, d.Name AS Text
                    FROM Dictionary d
                    INNER JOIN Category c ON d.CategoryId = c.Id
                    INNER JOIN Form f ON c.FormId = f.Id
                    WHERE f.Name = 'SOC' AND c.Name = 'Observer Title' AND 
                    d.IsActive = 1 AND c.IsActive = 1 AND f.IsActive = 1").ToList();

                var possibleObserverTypeList = new List<ObserverType>();
                foreach (var pItem in possibleObserverType)
                {
                    possibleObserverTypeList.Add(new ObserverType { Id = pItem.Id, Name = pItem.Text });
                }
                form.ObserverType = possibleObserverTypeList;                

                return form;
            }
        }

        [HttpGet]
        public ActionResult Index()
        {
            ViewData["Message"] = "Fill your safety observation card";
            
            return View(GetSOCForm());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(SOCForm form)
        {
            foreach (var item in form.Questions)
            {
                if (!item.SelectedAnswer.HasValue)
                {
                    form.IsQuestionSelected = false;
                    break;                    
                }
                else
                {
                    form.IsQuestionSelected = true;
                }
            }

            if (form.IsQuestionSelected)
            {
                if (ModelState.IsValid)
                {
                    SqlConnection conn = new SqlConnection();
                    conn.ConnectionString = configuration.GetConnectionString("DefaultConnection");

                    if (Request.Cookies["latitude"] != null && Request.Cookies["longitude"] != null &&
                        Request.Cookies["accuracy"] != null)
                    {
                        using (IDbConnection dbConnection = conn)
                        {
                            dbConnection.Open();
                            var observationType = conn.Query<string>(@"SELECT Name FROM Dictionary WHERE Id = @Id",
                                       new { @Id = form.SelectedObserverType.Value }).FirstOrDefault();

                            using (var trans = dbConnection.BeginTransaction())
                            {
                                try
                                {
                                    var socId = 0;
                                    socId = conn.Query<int>(@"INSERT INTO SOCDataV2 (Comments, Location, Observer, Task, ObservedBy, Latitude,
                                    Longitude, Accuracy, CreatedBy, CreatedDate, Timestamp)
                                    Values(@comments, @location, @observer, @task, @observedBy, @latitude, @longitude, @accuracy, @createdBy, 
                                    @createdDate, @timestamp) 
                                    SELECT SCOPE_IDENTITY() AS [SCOPE_IDENTITY];", new
                                    {
                                        @comments = form.Comments,
                                        @location = form.Location,
                                        @observer = form.Observer,
                                        @task = form.Task,
                                        @observedBy = observationType,
                                        @latitude = Convert.ToDecimal(Request.Cookies["latitude"]),
                                        @longitude = Convert.ToDecimal(Request.Cookies["longitude"]),
                                        @accuracy = Convert.ToInt32(Request.Cookies["accuracy"]),
                                        @createdBy = this.User.Identity.Name,
                                        @createdDate = DateTimeOffset.Now,
                                        @timestamp = DateTimeOffset.Now
                                    }, trans).SingleOrDefault();

                                    foreach (var item in form.Questions)
                                    {
                                        dbConnection.Execute(@"INSERT INTO SOCDataItemV2 (SOCDataId, QuestionId, AnswerId, CreatedBy,
                                        CreatedDate, Timestamp)
                                        Values(@SOCDataId, @QuestionId, @AnswerId, @CreatedBy, @CreatedDate, @Timestamp)", new
                                        {
                                            @SOCDataId = socId,
                                            @QuestionId = item.Id,
                                            @AnswerId = item.SelectedAnswer,
                                            @createdBy = this.User.Identity.Name,
                                            @createdDate = DateTimeOffset.Now,
                                            @timestamp = DateTimeOffset.Now
                                        }, trans);
                                    }

                                    trans.Commit();
                                    conn.Close();

                                    Response.Cookies.Delete("latitude");
                                    Response.Cookies.Delete("longitude");
                                    Response.Cookies.Delete("accuracy");

                                    return RedirectToAction("Index", "Home");
                                }
                                catch (Exception ex)
                                {
                                    trans.Rollback();
                                    conn.Close();
                                    return RedirectToAction("Error", ex);
                                }
                            }
                        }
                    }
                    else
                    {

DBI.Safety/DBI.Safety/Views/Shared/_Layout.cshtml
@using System.IO;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DBI.Safety</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Roboto:900' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto:100' rel='stylesheet' type='text/css'>

    <script>
        var options = {
            enableHighAccuracy: true,
            timeout: 5000,
            maximumAge: 0
        };

        navigator.geolocation.getCurrentPosition(positionSuccess, positionError, options);

        function positionSuccess(geo) {
            document.cookie = 'latitude=' + geo.coords.latitude;
            document.cookie = 'longitude=' + geo.coords.longitude;
            document.cookie = 'accuracy=' + geo.coords.accuracy;
        }

        function positionError(geo) {
            document.cookie = 'latitude=; expires=Thu, 01 Jan 1970 00:00:00 UTC;';
            document.cookie = 'longitude=; expires=Thu, 01 Jan 1970 00:00:00 UTC;';
            document.cookie = 'accuracy=; expires=Thu, 01 Jan 1970 00:00:00 UTC;';
        }
    </script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" style="border-bottom: 5px solid #ae8310;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">
                    <span>@Html.Raw(File.ReadAllText("wwwroot/images/Logo_pub.svg"))</span>
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            SOC
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" asp-area="" asp-controller="SOC" asp-action="Index">Create New SOC</a></li>
                            <li><a class="dropdown-item" asp-area="" asp-controller="SOC" asp-action="History">SOC History</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            FLHA
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" asp-area="" asp-controller="FLHA" asp-action="Index">Create New FLHA</a></li>
                            <li><a class="dropdown-item" asp-area="" asp-controller="FLHA" asp-action="History">FLHA History</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Admin
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="AddForm">Add New Form</a></li>
                            <li><a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="AddCategory">Add New Category</a></li>
                            <li><a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="AddDictionary">Add New Dictionary</a></li>
                        </ul>
                    </li>
                </ul>
                <p class="nav navbar-text navbar-right">Hello, @User.Identity.Name</p>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
    </div>
    <div class="footer navbar-fixed-bottom">
        <p>&copy; 2018 - DBi Services: Safety</p>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>